// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:slug": {
    params: {
      "slug": string;
    };
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/product/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:slug" | "/blog" | "/blog/:slug" | "/product/:slug";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/page.tsx": {
    id: "routes/page";
    page: "/:slug";
  };
  "routes/blog/index.tsx": {
    id: "routes/blog/index";
    page: "/blog";
  };
  "./routes/blog/post.tsx": {
    id: "routes/blog/post";
    page: "/blog/:slug";
  };
  "./routes/product/product.tsx": {
    id: "routes/product/product";
    page: "/product/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/page": typeof import("./src/./routes/page.tsx");
  "routes/blog/index": typeof import("./src/routes/blog/index.tsx");
  "routes/blog/post": typeof import("./src/./routes/blog/post.tsx");
  "routes/product/product": typeof import("./src/./routes/product/product.tsx");
};