import Head from 'next/head'
import { NextPageWithLayout } from './_app'
import { defineAppBaseLayout } from '../components/layouts/AppBaseLayout'
import { useModalStore } from '../components/common/Modal'
import Button from '../components/common/Button'
import { getAllPosts } from '../lib/posts'
import { InferGetStaticPropsType } from 'next'

const Home: NextPageWithLayout = (props: InferGetStaticPropsType<typeof getStaticProps>) => {
  const modalStore = useModalStore();
  return (
    <div className='h-full w-full'>

      <Head>
        <title>Hamish Weir Blog: Home</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className='text-white' onClick={() => modalStore.pushModal(<Button text='hello world'/>)}>Content placeholder</h1>
      </div>
    </div>
  )
}

Home.getLayout = defineAppBaseLayout
export default Home

export const getStaticProps = async () => ({
  props: {
    posts: getAllPosts()
  }
})
