import Head from 'next/head'
import { NextPageWithLayout } from './_app'
import { defineAppBaseLayout } from '../components/layouts/AppBaseLayout'
import { useModalStore } from '../components/common/Modal'
import Button from '../components/common/Button'
import { getAllPosts, Post } from '../lib/posts'
import { files } from '../lib/file'
import { Product, products } from '../lib/products'
import { InferGetStaticPropsType } from 'next'
import PostList from '../components/posts/PostList'

interface BlogProps {
  posts: Post[],
  products: Product[],
}

const Home: NextPageWithLayout<BlogProps> = (props) => {
  const modalStore = useModalStore();
  return (
    <div className='h-full w-full'>

      <Head>
        <title>Hamish Weir Blog: Home</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className='text-white' onClick={() => modalStore.pushModal(<Button text='hello world'/>)}>Content placeholder</h1>
        <PostList posts={props.posts}/>
        <p>{JSON.stringify([...props.posts, ...props.products])}</p>
      </div>
    </div>
  )
}

Home.getLayout = defineAppBaseLayout
export default Home

export const getStaticProps = async () => {

  const allPosts = getAllPosts()

  const allProducts = products.getAll()
    .slice(0,20)
    .map(descriptor => products.getById(descriptor.id))
    .filter(product => product === undefined)

  return ({
    props: {
      posts: allPosts,
      products: allProducts,
    }
  })
}
